blank_issues_enabled: false
contact_links:
  - name: GitLab bug tracker
    url: https://gitlab.com/IvanSanchez/homeassistant-sensorthings/-/issues
    about: >
      Development of `homeassistant-sensorthings` happens mostly on Git**Lab**, not
      Git**Hub**. If you wish to report a problem, please do so in the issue
      tracker at the GitLab repository.
